appname: transfdoc
prefixurl: 0.0.0.0:8080
runmode: debug
logsavepath: logs/
logsavename: log
loglevel: debug
logfileext: log
timeformat: 20060102
apikey: 06f5a93cbfe1c481d0fc20cf7d6692b92034679355
apitoken: 061f631ecd83adaef9d91ed3616f7db71466087183
showdocurl: https://www.showdoc.cc/server/api/item/updateByApi
showdocopen: true
mysql:
    address:
    dbname:
    username:
    password:
    maxconns:
    maxidleconns:
    connmaxlifetime:

